### ISSUE TITLE
Provide shortcuts when the passed data type conforms to a Standard text streaming protocol

### ISSUE THREAD

**Issue by CTMacUser** [marcusrossel/data-field#1]
Your main type and its two implementation types take conversion closures between the data type and `String` (in both directions).  There are protocols in the Swift Standard Library that deal with such conversions.

We can provide an extension for `DataField` (and `DataField.Unsafe`) to types conforming to `CustomStringConvertible` for an initializer that drops the `dataToText` field so it can use the data type's outward string conversion.  We can provide another extension for `DataField`(`.Unsafe`) for types that also conform to `LosslessStringConvertible` for an initializer that drops the `textToData` field so it can use the data type's inward string conversion.  (The first new initializer forwards to the current initializer.  The second new initializer forwards to the first new initializer, because `LosslessStringConvertible` refines `CustomStringConvertible`.)

**Comment by CTMacUser** [comment]
Technically, you don't need to watch on `CustomStringConvertible & LosslessStringConvertible` because the latter protocol is a refinement of the former.  (I'm surprised the compiler doesn't give a warning.)

**Comment by marcusrossel** [comment]
Oh, thanks for bringing that up. I thought `LosslessStringConvertible` was unidirectional.

**Comment by marcusrossel** [comment]
This is now fixed in release v0.3.1.
